### ISSUE TITLE
ceteris_paribus function doesn't work for a classification model 

### ISSUE THREAD

**Issue by KasiaKobylinska** [pbiecek/ceterisParibus#1]
ceteris_paribus function does not work when the explainer contains a classification model:

>\> p_fun <- function(object, newdata){predict.randomForest(object, newdata=newdata, type="prob")[,2]}
>\> explainer_rf_ceteris <- DALEX::explain(model ,data = train_data[,-n], y = train_data[,n]), predict_function = pfun)

>\> wi_rf <- ceteris_paribus(explainer_rf_ceteris, observation = new_patient)

>Błąd w poleceniu 'predict_function(model, newdata = new_data)':
nieużywany argument (newdata = new_data)
Enter a frame number, or 0 to exit   
1: ceteris_paribus(explainer_rf_ceteris, observation = new_patient)
2: #13: lapply(names_to_present, function(vname) {
    probs <- seq(0, 1, length.out = grid_points)
    new_x <- quantile(data[, vname], probs = pr
3: FUN(X[[i]], ...)
4: #19: data.frame(y_hat = predict_function(model, newdata = new_data), new_x = new_x, vname = vname, x_quant = quant_x, quant = probs, relative_qu

**Comment by pbiecek** [comment]
@KasiaKobylinska Alicja fixed this issue in e4136ea
