### ISSUE TITLE
Error in what_if plot with color="_vname_"

### ISSUE THREAD

**Issue by kmichael08** [pbiecek/ceterisParibus#16]
I can't reproduce commands like: `plot(cp_rf, color = "_vname_")` from https://pbiecek.github.io/ceterisParibus/articles/whatIf1d.html.
There's a problem with parameter `color_points`, as changing it into `plot(cp_rf, color = "_vname_", color_points='black')` makes this work.

Full error message below:
Error in `[.data.frame`(all_observations, , color_points): undefined columns selected
Traceback:

1. plot(cp_rf, color = "_vname_")
2. plot.ceteris_paribus_explainer(cp_rf, color = "_vname_")
3. ceteris_paribus_layer(x = x, ..., size = size, alpha = alpha, 
 .     color = color, size_points = size_points, alpha_points = alpha_points, 
 .     color_points = color_points, size_rugs = size_rugs, alpha_rugs = alpha_rugs, 
 .     color_rugs = color_rugs, size_residuals = size_residuals, 
 .     alpha_residuals = alpha_residuals, color_residuals = color_residuals, 
 .     only_numerical = only_numerical, show_profiles = show_profiles, 
 .     show_observations = show_observations, show_rugs = show_rugs, 
 .     show_residuals = show_residuals, aggregate_profiles = aggregate_profiles, 
 .     facet_ncol = facet_ncol, selected_variables = selected_variables, 
 .     init_plot = TRUE, as.gg = as.gg)(NULL)
4. lapply(vnames, function(var) {
 .     data.frame(`_x_` = all_observations[, var], `_vname_` = var, 
 .         `_yhat_` = all_observations$`_yhat_`, `_y_` = if (is.null(all_observations$`_y_`)) 
 .             NA
 .         else all_observations$`_y_`, `_color_` = if (!is_color_points_a_variable) 
 .             NA
 .         else all_observations[, color_points], 0, `_label_` = all_observations$`_label_`)
 . })
5. FUN(X[[i]], ...)
6. data.frame(`_x_` = all_observations[, var], `_vname_` = var, 
 .     `_yhat_` = all_observations$`_yhat_`, `_y_` = if (is.null(all_observations$`_y_`)) NA else all_observations$`_y_`, 
 .     `_color_` = if (!is_color_points_a_variable) NA else all_observations[, 
 .         color_points], 0, `_label_` = all_observations$`_label_`)
7. all_observations[, color_points]
8. `[.data.frame`(all_observations, , color_points)
9. stop("undefined columns selected")

**Comment by pbiecek** [comment]
@kmichael08 Works for me. Would you share `devtools::session_info()` ?

**Comment by kmichael08** [comment]
Installing directly from github solved the problem.
It failed on:
[failed_session.txt](https://github.com/pbiecek/ceterisParibus/files/2492030/failed_session.txt)
