### ISSUE TITLE
Plot subset of variables

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/ceterisParibus#3]
It would be great if there was a possibility for generating plots for the subset of variables.
I was using cp plots for the model with 35 variables and it was difficult to read anything.

I'm not sure if it's better to add such parameter to ceteris_paribus() or plot().

**Comment by pbiecek** [comment]
It is added to ceteris_paribus() as the `selected_variables` argument

```
wi_rf <- ceteris_paribus(explainer_rf, observation = new_apartment,
         selected_variables = c("surface", "floor", "no.rooms"))
```

**Comment by agosiewska** [comment]
Thank you
