### ISSUE TITLE
Ceteris Paribus VS ICE & PDP

### ISSUE THREAD

**Issue by echo66** [pbiecek/ceterisParibus#6]
Greetings! 

I'm trying to understand what is the difference between the Ceteris Paribus plots and ICE/PDP. It seems (almost?) the exact same thing.

**Comment by pbiecek** [comment]
They are similar, but:
CP plot shows many variables and single observations
ICE plot shows single variable many observations
PDP plot shows single variable average from many observations

**Comment by echo66** [comment]
AFAIK, CP is like ICE when you just plot the response for a single observation. Am I correct?

**Comment by pbiecek** [comment]
For a single observation, ICE plots usually shows effect of only one variable, while CP shows effect of many variables (many colours).
But the mechanic and presented values are the same. CPs show few ICEplots in a single chart

**Comment by echo66** [comment]
Thanks for the explanation, @pbiecek . :smile:
